[package]
name        = "tokio-nsq"
version     = "0.14.1"
authors     = ["Harpo Roeder <roedeharpo@protonmail.ch>"]
edition     = "2024"
license     = "BSD-3-Clause"
repository  = "https://github.com/harporoeder/tokio-nsq"
description = "A Rust NSQ client built on Tokio. Tokio NSQ aims to be a feature complete NSQ client implementation."
readme      = "README.md"
categories  = ["asynchronous", "network-programming", "concurrency"]

[dependencies]
reqwest           = {version = "0.12.22", features = ["json"]}
tokio             = { version = "1.46.0", features = ["full"] }
serde             = { version = "1.0.219", features = ["derive"] }
serde_json        = "1.0.140"
byteorder         = "1.5.0"
anyhow            = "1.0.98"
thiserror         = "2.0.12"
log               = "0.4.27"
tokio-rustls      = "0.26.2"
rustls            = "0.23.28"
regex             = "1.11.1"
lazy_static       = "1.5.0"
backoff           = "0.4.0"
gethostname       = "1.0.2"
snap              = "1.1.1"
matches           = "0.1.10"
async-compression = { version = "0.4.25", features = ["tokio", "deflate"] }
tokio-io-timeout  = "1.2.0"
futures-util      = "0.3.31"
futures           = "0.3.31"
bytes             = "1.10.1"

[dev-dependencies]
rand       = "0.9.1"
env_logger = "0.11.8"

[build-dependencies]
built = "0.8.0"
